name: "CI for burger" # Готовим бургер

on: [push] # Триггер

jobs:
  cooking: # Название этапа. В нащем случае "Готовка"
    runs-on: ubuntu-latest 
    # runs-on: это OC в котором будет запускаться этап 
    # пока оставляем его значение как ubuntu-latest
	steps:
	  - name: Достать булочку
        run: |
          echo "🍞 Достаем булочку"
          
      - name: Пожарить котлету
        run: |
          
name: "CI for burger" # Готовим бургер

on: [push] # Триггер

jobs:
  cooking: # Название этапа. В нащем случае "Готовка"
    runs-on: ubuntu-latest 
    # runs-on: это OC в котором будет запускаться этап 
    # пока оставляем его значение как ubuntu-latest
	steps:
	  - name: Достать булочку
        run: |
          echo "🍞 Достаем булочку"
          
      - name: Пожарить котлету
        run: |
	  echo "🥩 Жарю котлету 5 минут"
          
	  - name: Собрать бургер
        run: |
          echo "🍔 Собираю бургер: булочка + котлета + сыр"
  
  sale: # Этап продажи бургера
    runs-on: ubuntu-latest 
    steps:
	  - name: Отправить на кассу
        run: |
          echo "🙋‍♂️ Отправить на кассу"
          
      - name: Выдать бургер клиенту
        run: |
          echo "🍜 Выдать бургер клиенту"
          
      - name: Получить оплату
        run: |
          echo "💰 Получить оплату"
